# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CIE 300\Semester 2\Parallel Algorithms\Project\exe\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.grpConfig = QtWidgets.QGroupBox(self.centralwidget)
        self.grpConfig.setMinimumSize(QtCore.QSize(0, 123))
        self.grpConfig.setObjectName("grpConfig")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpConfig)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnDisconnect = QtWidgets.QPushButton(self.grpConfig)
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.gridLayout_2.addWidget(self.btnDisconnect, 2, 2, 1, 1)
        self.txtIP = QtWidgets.QLineEdit(self.grpConfig)
        self.txtIP.setObjectName("txtIP")
        self.gridLayout_2.addWidget(self.txtIP, 1, 1, 1, 2)
        self.lblIP = QtWidgets.QLabel(self.grpConfig)
        self.lblIP.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIP.setObjectName("lblIP")
        self.gridLayout_2.addWidget(self.lblIP, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.grpConfig)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.grpConfig)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.grpConfig)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_2.addWidget(self.btnConnect, 2, 1, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.grpConfig)
        self.txtName.setObjectName("txtName")
        self.gridLayout_2.addWidget(self.txtName, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.grpConfig)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.grpConfig, 0, 0, 1, 1)
        self.grpChat = QtWidgets.QGroupBox(self.centralwidget)
        self.grpChat.setObjectName("grpChat")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpChat)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtSend = QtWidgets.QLineEdit(self.grpChat)
        self.txtSend.setObjectName("txtSend")
        self.gridLayout_3.addWidget(self.txtSend, 1, 0, 1, 1)
        self.btnSend = QtWidgets.QPushButton(self.grpChat)
        self.btnSend.setObjectName("btnSend")
        self.gridLayout_3.addWidget(self.btnSend, 1, 1, 1, 1)
        self.lstChat = QtWidgets.QListWidget(self.grpChat)
        self.lstChat.setObjectName("lstChat")
        self.gridLayout_3.addWidget(self.lstChat, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.grpChat, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpConfig.setTitle(_translate("MainWindow", "Configuration"))
        self.btnDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.lblIP.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "Your IP:"))
        self.label.setText(_translate("MainWindow", "Server IP:"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "Your Name:"))
        self.grpChat.setTitle(_translate("MainWindow", "Chat"))
        self.btnSend.setText(_translate("MainWindow", "Send"))
